# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kwd',
            options={'ordering': ('-modify_date',), 'verbose_name': 'KWDs'},
        ),
        migrations.AddField(
            model_name='kwd',
            name='content',
            field=models.TextField(blank=True, verbose_name='간략한 소개'),
        ),
        migrations.AddField(
            model_name='kwd',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kwd',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 날짜'),
        ),
    ]
