# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0002_auto_20170621_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kwd',
            options={'ordering': ('-modify_date',), 'verbose_name': 'KWD', 'verbose_name_plural': 'KWDs'},
        ),
        migrations.AddField(
            model_name='kwd',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koreawebdesign.Category'),
        ),
    ]
