# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0003_auto_20170621_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='kwd',
            name='category',
        ),
        migrations.AddField(
            model_name='kwd',
            name='category',
            field=models.ManyToManyField(null=True, to='koreawebdesign.Category'),
        ),
        migrations.AddField(
            model_name='kwd',
            name='color',
            field=models.ManyToManyField(null=True, to='koreawebdesign.Color'),
        ),
    ]
