# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0004_auto_20170621_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwd',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='koreawebdesign.Category'),
        ),
        migrations.AlterField(
            model_name='kwd',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='koreawebdesign.Color'),
        ),
    ]
