# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:24
from __future__ import unicode_literals

from django.db import migrations
import koreawebdesign.fields


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0006_auto_20170622_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwd',
            name='image',
            field=koreawebdesign.fields.ThumbnailImageField(default=1, upload_to='photo/%Y/%m'),
            preserve_default=False,
        ),
    ]
