# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:47
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('koreawebdesign', '0007_kwd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwd',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
